export const GET_TODAY_WEATHER = 'GET_TODAY_WEATHER';
export const GET_TODAY_WEATHER_SUCCESS = 'GET_TODAY_WEATHER_SUCCESS';
export const GET_TOMORROW_WEATHER = 'GET_TOMORROW_WEATHER';
export const GET_TOMORROW_WEATHER_SUCCESS = 'GET_TODAY_TOMORROW_SUCCESS';
